#!/usr/bin/env julia
#
# Called by git-commit with no arguments.  This checks to make sure that all
# .jl files are indented correctly before a commit is made.
#
# To enable this hook, make this file executable and copy it in
# $GIT_DIR/hooks.
#
# This is adapted from .dev/hooks/pre-commit from ClimateMachine.jl with the
# following license:
#
#    Copyright 2019 Climate Modeling Alliance
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

toplevel_directory = chomp(read(`git rev-parse --show-toplevel`, String))

using Pkg
Pkg.activate(joinpath(toplevel_directory, ".dev"))
Pkg.instantiate()

using JuliaFormatter

include(joinpath(toplevel_directory, ".dev", "formatter_options.jl"))

needs_format = false

for diffoutput in split.(readlines(`git diff --name-status --cached`))
    status = diffoutput[1]
    filename = diffoutput[end]
    (!startswith(status, "D") && endswith(filename, ".jl")) || continue

    a = read(`git show :$filename`, String)
    b = format_text(a; formatter_options...)

    if a != b
        fullfilename = joinpath(toplevel_directory, filename)

        @error """File $filename needs to be indented with:
            julia $(joinpath(toplevel_directory, ".dev", "format.jl")) $fullfilename
        and added to the git index via
            git add $fullfilename
        """
        global needs_format = true
    end
end

exit(needs_format ? 1 : 0)
