name: linux

on:
  push:
    branches:
          - master
          - staging
          - trying
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.4

    - name: Install Project Packages
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.build()'

    - name: Tests
      run: |
        julia --project=@. -e 'using Pkg; Pkg.test()'
